name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'

    - name: Compile and test
      run: |
        mkdir -p build/classes
        javac -cp "src/main/java:src/test/java:lib/*" -d build/classes $(find src/main/java src/test/java -name "*.java")
        java -cp "build/classes:lib/*" org.junit.runner.JUnitCore $(find build/classes -name "*Test*.class" | sed 's/build\/classes\///' | sed 's/\//./g' | sed 's/\.class//')

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results
